### PR TITLE
Error in supplier notation

### PR DESCRIPTION
**Pull request by equinoxefr**
Notation rating is bad. It's on 5, not 10.

Regards

### CODE REVIEW

**Comment by wawax** [comment]
@tsmr  would you please check that ?
Thank you.

**Comment by trasher** [comment]
Related to #76

**Comment by trasher** [comment]
@tsmr ping?

**Comment by wawax** [comment]
@tsmr are you alive ?
it's a PR on one of the feature you've developed.

thank you in advance.

**Pull request merged**
