### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by Rom1-B**
Add CI

### CODE REVIEW

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
I think you are missing the required php dependencies.

For example, here are the depencies of the tag plugin: https://github.com/pluginsGLPI/tag/blob/main/composer.json

edit: if you added the eslinted too, don't forget about client side dependencies too.

**Comment by AdrienClairembault** [comment]
image

**Review by stonebuzz — APPROVED** [review]
complicated to review but ok

**Comment by Rom1-B** [comment]
Too much code to modify for PHPStan, I think we'll have to dedicate a PR for its activation. `phpstan.neon` is created but ignores several cases, so as not to lose what I'd already done.

**Review by AdrienClairembault — APPROVED** [review]

**Pull request merged**
